project:
  name: cfn-abi-spotbynetapp-cloudcheckr
  owner: kjordan@netapp.com
  package_lambda: true
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
 
  - us-east-1

tests:
  sample:
    parameters:
      pAPIKey: "$[taskcat_getenv(MY_API_KEY)]"
      pAPISecret: "$[taskcat_getenv(MY_API_SECRET)]"
      pBillingBucketName: 'billingbucket'
      pCloudTrailBucketName: 'cloudtrailbucket'
      pCurBucketName: 'curbucket'
      pCustomerNumber: '54687'
      pSRASourceS3BucketName: 'kurtspublicbucket'
      pSRAStagingS3Key: 'cfn-abi-spotbynetapp-cloudcheckr'


      
    regions:
    - us-east-1
    template: templates/CCBuiltIn.yaml
