project:
  name: cfn-abi-spotbynetapp-cloudcheckr
  owner: kjordan@netapp.com
  package_lambda: true
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
 
  - us-east-1

tests:
  sample:
    parameters:
      APIKey: "$[taskcat_getenv(MY_API_KEY)]"
      APISecret: "$[taskcat_getenv(MY_API_SECRET)]"
      BillingBucketName: 'billingbucket'
      CloudTrailBucketName: 'cloudtrailbucket'
      CurBucketName: 'curbucket'
      CustomerNumber: '54687'


      
    regions:
    - us-east-1
    template: templates/CCBuiltIn.yml
