project:
  name: cfn-abi-spotbynetapp-cloudcheckr
  owner: kjordan@netapp.com
  package_lambda: true
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1

tests:
  sample:
    parameters:
      pAPIKey: $[taskcat_ssm_/cloudcheckr/api_key]
      pAPISecret: $[taskcat_ssm_/cloudcheckr/api_secret]
      pABISourceS3BucketName: $[taskcat_autobucket]
      pABIStagingS3Key: $[taskcat_project_name]
      pCloudTrailBucketName: $[taskcat_ssm_/cloudcheckr/cloudtrail_bucket_name]
      pCurBucketName: $[taskcat_ssm_/cloudcheckr/cur_bucket_name]
      pCustomerNumber: $[taskcat_ssm_/cloudcheckr/customer_number]
    regions:
    - us-east-1
    template: templates/CCBuiltIn.yaml
