project:
  name: cfn-abi-spotbynetapp-cloudcheckr
  owner: kjordan@netapp.com
  package_lambda: true
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
 
  - us-east-1

tests:
  sample:
    parameters:
      pAPIKey: '88e84dcd-f2dd-4dd0-96c0-113c86982992'
      pAPISecret: '3TTeI5IaAFes!!!1lxq80h!Qh!8hpzP0'
      pBillingBucketName: 'billingbucket'
      pCloudTrailBucketName: 'cloudtrailbucket'
      pCurBucketName: 'curbucket'
      pCustomerNumber: '54687'
      pSRASourceS3BucketName: 'kurtspublicbucket'
      pSRAStagingS3Key: 'cfn-abi-spotbynetapp-cloudcheckr'


      
    regions:
    - us-east-1
    template: templates/CCBuiltIn.yaml
