project_id: 'abip-1kirFQBF75MfEQ3RbMQHRb-6zslZiD89tzGorqVfIMUxZ-ln89tl1p'
project_name: 'ABI SpotByNetApp CloudCheckr'
project_code: 'd7ee8559-8204-4c5e-b622-46673a0d08bb'
project_type: 'ABI CloudFormation Project Type'
partner_name: 'Spot by NetApp'
launch_date: '2023-10-04'
repo_name: 'cfn-abi-spotbynetapp-cloudcheckr'
templates_info:
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-6zslZiD89tzGorqVfIMUxZ-ln89tltm'
    file_name: 'templates/CCBuiltIn.yaml'
    count_flag: 'true'
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-6zslZiD89tzGorqVfIMUxZ-ln89tmlj'
    file_name: 'templates/cciamrole/cc_aws_cfn_iam_stack.template.json'
    count_flag: 'false'